# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: sync

on:
  schedule:
    - cron: '35 4 * * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: git clone
      timeout-minutes: 5
      run: |
        git clone --depth 1 -b master https://github.com/v2fly/domain-list-community upstream_repo
    - name: run py
      run: |
        python3 a/b.py
    - name: Commit and Push
      run: |
        rm -rf upstream_repo
        mkdir -p deploy/rule
        cp -r txt/* deploy/rule/
        cd deploy/
        
        git init
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add .
        export TZ='Asia/Shanghai'
        git commit -m "Auto-transform rules: $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:dev